'\" tp
.\" -*- nroff -*-
.
.TH GROPDF-OTF 7
.
.de vs.ex
.  nr VS.bak \\n[VS]
.  nr VS (\\n[PS] * 120 / 100)
.  vs \\n[VS]u
..
.
.de vs.ja
.  nr VS.bak \\n[VS]
.  nr VS (\\n[PS] * 180 / 100)
.  vs \\n[VS]u
..
.
.de vs.bak
.  nr VS \\n[VS.bak]
.  vs \\n[VS]u
..
.
.am1 EX
.in +1m
.ps -0.5
.sp .3
.vs.ex
..
.am1 EE
.ps +0.5
.in -1m
.vs.bak
..
.
.ds MF B\" man page topic font
.
.\" ------------------------------------------------------------------
.SH NAME
.\" ------------------------------------------------------------------
.
gropdf-otf \- gropdfでOTFを使う
.
.ig
.\" ------------------------------------------------------------------
.SH SYNOPSYS
.\" ------------------------------------------------------------------
.
.EX
git clone https://github.com/obuk/gropdf-otf.git
cd gropdf-otf
vagrant up
vagrant ssh
make -C /vagrant gropdf-otf.7.pdf
.EE
..
.
.\" ------------------------------------------------------------------
.SH 日本語のフォントを使う
.\" ------------------------------------------------------------------
groffで日本語のフォント(OTF)を使用して、
日本語のPDFを出力します。
.PP
日本語のフォントはOTFやTTFが多いと思いますが、
.UR https://manpages.ubuntu.com/manpages/plucky/man1/gropdf.1.html
.MR gropdf 1
.UE
と
.UR https://manpages.ubuntu.com/manpages/plucky/man1/afmtodit.1.html
.MR afmtodit 1
.UE
はPostScriptフォントを要求するため、
TTFをPostScriptフォントに変換する (以前試したものが
.UR https://github.com/obuk/use-groff
use-groff
.UE
にあります)、
あるいは、gropdfとafmtoditにOTFをサポートするための変更を加えます。
ここでは後者を試します。
.
.\" ------------------------------------------------------------------
.SS 日本語フォントのインストール
.\" ------------------------------------------------------------------
.
.UR https://github.com/trueroad/HaranoAjiFonts
原ノ味フォント
.UE \c
を明朝 M\fIx\fP、ゴチック G\fIx\fP、等幅 Code\fIx\fP
としてインストールする例を示します。(\fIx\fP はスタイル)
.EX
$ \f(CBmake -f font-haranoaji.mk clean install\fP	# 明朝 M\fIx\fP、ゴチック G\fIx\fP
.ig
$ \f(CBtime make -f font-haranoaji.mk clean install\fP  # 明朝 M\fIx\fP、ゴチック G\fIx\fP
real	0m47.377s
user	0m40.210s
sys	0m4.274s
..
$ \f(CBmake -f font-haranoaji-code.mk clean install\fP	# 等幅 Code\fIx\fP
.ig
$ \f(CBtime make -f font-haranoaji-code.mk clean install\fP	# 等幅 Code\fIx\fP
real	0m11.074s
user	0m9.339s
sys	0m1.424s
..
.EE
M\fIx\fP とG\fIx\fP でインストールされるスタイルは
R, I, B, BI (横書) と V, IV, BV, BIV (縦書) です。
.
.PP
人名漢字も使用する場合は、更に
.UR https://moji.or.jp/mojikiban/font/
IPAmj明朝フォント
.UE \c
をインストールします。
(スタイルはRのみ)
.
.EX
$ \f(CBmake -f font-ipamj.mk\fP
.EE
.
.ig
.PP
IPAmj明朝フォントの異体字は、「基底文字+異体字セレクタ」という形式で表
わされますが、ToUnicode CMapで対応付けても表示されません。対処するには
フォントを埋め込まなければなりません。
..
.
.\" ------------------------------------------------------------------
.SS OTF のサポート
.\" ------------------------------------------------------------------
.
gropdfとafmtoditでOTF\u\s-2[1]\s0\dをサポートします。
その際、gropdfにはPDFのTmオペレータ\u\s-2[2]\s0\dを使用して
斜体や縦書を出力する変更も加えます。
そのため、字体の描画に必要なフォントは正体のみあれば十分ですが、
groff用のフォント記述ファイル
.UR https://manpages.ubuntu.com/manpages/plucky/man5/groff_font.5.html
.MR groff_font 5
.UE
はすべてのスタイルについて作成する必要があります。
.
.PP
groff_fontを作成するツールotftoditの基本的な使い方は次のとおりです。
.EX
$ \f(CBtx -afm font.otf >font.afm\fP	\
# afdko をインストールする必要があります。
$ \f(CBotftodit font.otf font.afm\s-2\dopt\u\s0 text.map groff_font\fP
.EE
.
.ig
.UR https://manpages.ubuntu.com/manpages/plucky/man1/troff.1.html
.MR troff 1
.UE
.IP
.I name metrics type code
.RI [ entity-name ]
.RB [ \-\-
.IR comment ]
.in
..
.
.PP
OTFからgroff_font (R正体、I斜体、V縦書) を作成する例を示します。
.EX
$ \f(CBOTF=HaranoAjiMincho-Regular.otf\fP
$ \f(CBotftodit.pl -c -F palt="*,*,palt" $OTF text.map MR\fP    # 正体
$ \f(CBotftodit.pl -c -F palt="*,*,palt" -i 50 -m -a 12 $OTF text.map MI\fP \
\e\(dq 斜体
$ \f(CBotftodit.pl -c -F palt="*,*,vpal" -F vert="*,*,vrt2" -V $OTF text.map MV\fP \
\e\(dq 縦書
.EE
.
opentype機能は、オプション \-F と \-V で指定します。
使い方についてはまだ決めかねています。
必要ならmakefileを確認してください。
.
.PD 0
.IP \u\s-2[1]\s0\d 3
OTFの読み取りに
.UR https://github.com/obuk/font-ttf
Font::TTF
.UE
を使用します。
日本語OTFでは
.UR https://learn.microsoft.com/ja-jp/typography/opentype/spec/cff
CFF
.UE
をサポートする必要があります。
.
.IP \u\s-2[2]\s0\d
座標変換の例が
.UR https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#page=126
Figure 13 \- Effects of Coordinate Transformations
.UE
にあります。
.
.
.\" ------------------------------------------------------------------
.SS ToUnicode CMap
.\" ------------------------------------------------------------------
.
ToUnicode CMap (cmapfile) は、gropdfの \-uオプションで指定できます。
ただし、OTFのcmapテーブルで
1つのグリフに複数のunicodeが対応付けられている場合は、
入力のグリフ名uXXXXからunicode値を得るのが自然です。
従って、cidフォントでは \-uオプションを無視し、
CMapは内部で作成します。
.
.PP
また、CMapで各cidに対応付けるunicode文字列には
分解されたもの decomposed unicode ではなく、
合成されたもの precomposed unicode を使います。
.
evinceでフォントが埋め込まれていないPDFを表示した場合に、
cidに対応付けられたunicode文字列の2文字目以降が表示されない問題を
軽減します。
.\"問題が解決しない場合は、フォントの埋め込みを検討してください。
.
.PP
unicodeの合成には
.UR https://metacpan.org/pod/Unicode::Normalize
Unicode::Normalize
.UE
のNFCが利用できますが、NFCは正規化も行います。
正規化は、たとえば、
「視 \f(CW\e[u8996]\fP」の旧字
「視 \f(CW\e[uFA61]\fP」
.\"「\[uFA61] (\f(CW\e[uFA61]\fP)」
.\"「\[u8996_E0101] (\f(CW\e[u8996_E0101]\fP)」
を「視 \f(CW\e[u8996]\fP」に変えてしまいます。
私には旧字が必要なので、とりあえず、
CJK互換漢字 F900\-FAFFと
CJK互換漢字補助 2F800\-2FA1F
については NFC を呼び出さないようにしています。
.
.\" ------------------------------------------------------------------
.SS PFB と OTF の比較
.\" ------------------------------------------------------------------
.
日本語のフォントのインストール時間、日本語のマンページ
.UR https://manpages.ubuntu.com/manpages/plucky/ja/man7/groff.7.html
.BR groff (7)
.UE
のPDF作成時間等を次表に示します。
.
.RS +2
.TS
tab(;);
lw(22) cw(8) cw(8) cw(8) cw(8).
;PFB;OTF;\(<-;\(<-
_
.T&
l r r c c.
T{
フォントのインストール時間
T};8m38.3s;47.4s;\(<-;\(<-
.T&
l r r r r.
T{
groff.7.pdf の作成時間
T};5.1s;11.0s;8.0s\u\s-2(1)\s0\d;5.0s\u\s-2(2)\s0\d
.T&
l r r c r.
T{
groff.7.pdf のファイルサイズ
T};563,078;361,277;\(<-;111,783\u\s-2(2)\s0\d
_
.TE
.PP
PFBのインストールには
.UR https://github.com/obuk/use-groff
font-saurce.mk
.UE 、
OTFには
.UR https://github.com/obuk/gropdf-otf
font-haranoaji.mk
.UE
を使いました。
.RE
.PP
PDFの作成時間を
.UR https://metacpan.org/pod/Devel::NYTProf
Devel::NYTProf
.UE
で調べると、OTFではフォントの埋め込みに時間を費していました。
pyftsubsetを呼び出しているからです。
作成時間を短縮するには、(1) 埋め込みを複数プロセスで実行する、
(2) 埋め込みを抑止する (pyftsubsetを呼び出さない)
等の方法が考えられます
(結果は上の表、および下記pdffontsの出力を参照のこと)。
.
(2) は効果が大きいのですが、
PDFに埋め込まれていないフォントはPDFビューワが解決する必要があります。
たとえば、evinceでは
.UR https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
fonts-conf
.UE
を設定する必要があります。
.
.
.EX
$ \f(CBtime zcat $(man -Lja -w groff.7) | env GROFF_BIN_PATH=/usr/local/bin \e
  groff -Tpdf -ktp -mja -mandoc - > groff.7.pdf\fP
real	0m4.979s
user	0m6.523s
sys	0m0.123s
$ \f(CBls -l groff.7.pdf\fP
-rw-rw-r-- 1 vagrant vagrant 111783 May 26 01:37 groff.7.pdf
$ \f(CBpdffonts groff.7.pdf\fP
name                         type          encoding     emb sub uni object ID
---------------------------- ------------- ------------ --- --- --- ---------
Symbol                       Type 1        Custom       no  no  no      79  0
Helvetica-Bold               Type 1        Custom       no  no  yes     82  0
Times-Bold                   Type 1        Custom       no  no  yes     85  0
Times-Italic                 Type 1        Custom       no  no  yes     88  0
Times-Roman                  Type 1        Custom       no  no  yes     91  0
Courier                      Type 1        Custom       no  no  yes     94  0
Courier-Oblique              Type 1        Custom       no  no  yes     97  0
Courier-Bold                 Type 1        Custom       no  no  yes    100  0
HaranoAjiMincho-Medium       CID Type 0    Identity-H   no  no  no     103  0
HaranoAjiGothic-Regular      CID Type 0    Identity-H   no  no  no     105  0
HaranoAjiMincho-Heavy        CID Type 0    Identity-H   no  no  no     107  0
HaranoAjiGothic-Bold         CID Type 0    Identity-H   no  no  no     109  0
.EE
.
.ig
.PP
pdffontsの出力からHaranoAjiMincho-MediumはToUnicode mapなしに見えますが、
103 0 objにはDescendantFonts 114 0 objがあり、CIDSystemInfoが得られます。
cidとunicodeの対応は、
.UR https://github.com/adobe-type-tools/cmap-resources
https://github.com/adobe-type-tools/cmap-resources
.UE
で見つけることができます。
.
.PP
先にPDFの作成時間は、埋め込みフォントの作成に時間を費していると書きましたが、
フォントの読み取りにも時間を費しています。
試しにgroff.7.pdfの作成にNotoフォントを使用すると、
時間はおよそ5秒 \(-> 16秒になります。
.
.EX
$ perl files/cttc.pl /usr/share/fonts/opentype/noto/NotoSerifCJK-Regular.ttc 0 \e
  >NotoSerifCJKjp-Regular.otf
$ ls -l HaranoAjiMincho-Regular.otf NotoSerifCJKjp-Regular.otf 
-rw-rw-r-- 1 vagrant vagrant  6420628 Nov 23  2024 HaranoAjiMincho-Regular.otf
-rw-rw-r-- 1 vagrant vagrant 24460560 May 25 09:50 NotoSerifCJKjp-Regular.otf
.EE
..
.\" ------------------------------------------------------------------
.SH 日本語の表示例
.\" ------------------------------------------------------------------
.
.\" ------------------------------------------------------------------
.SS 縦書斜体
.\" ------------------------------------------------------------------
.
NHK BS シネマ「昼下りの情事」から探偵事務所の看板とその字幕を示します。
(開始から5分くらい)
.br
.mk
.sp -0.6
.PS
box_w = 1.8
box_h = 1.3
pin_r = 0.02
gap = 0.02
.vs 13p
BOX: box width box_w height box_h \
"" \
"\u\s+2CLAUDE CHAVASSE\s0\d" \
"\f(HR\s+2D\('EECTIVE PRIV\('E\s0\fP" \
"\f(HR\s-2DISCR\('ETION ASSUR\('EE\s0\fP" \
"\f(HR2\Z'\u\s-4\(`eme\s0\d'\h[0.4m]-\h[0.6m]E\s-2TAGE\s0\fP"
.vs
.\" pins at the corners
e2p = pin_r + gap
err = 0.07 + pin_r
move to BOX.nw down -err; move right e2p down  e2p; A: circle radius pin_r
move to BOX.sw down -err; move right e2p down -e2p; B: circle radius pin_r
move to BOX.se down -err; move left  e2p down -e2p; C: circle radius pin_r
move to BOX.ne down -err; move left  e2p down  e2p; D: circle radius pin_r
.\" lines between pins
hline_len = box_w - pin_r * 2 * 2 - gap * 2
vline_len = box_h - pin_r * 2 * 2 - gap * 2
move to A.b; move down  gap; AB: line down  vline_len - gap * 2
move to B.r; move right gap; BC: line right hline_len - gap * 2
move to C.t; move up    gap; CD: line up    vline_len - gap * 2
move to D.l; move left  gap; DA: line left  hline_len - gap * 2
.\" splines between lines
move to AB.b; spline right gap then right pin_r down  pin_r then down  gap
move to BC.r; spline up    gap then up    pin_r right pin_r then right gap
move to CD.t; spline left  gap then left  pin_r up    pin_r then up    gap
move to DA.l; spline down  gap then down  pin_r left  pin_r then left  gap
.\" subtitle
move to BOX.sw down 0.1
line right box_w "\f[HI]生活は ごくまともだ\fP" invis
.\" vertical subtitle
cjk_puncts = 0
show_guide = 0
move to BOX.ne; move right 0.2 down 0.07
if (cjk_puncts) then {
  line down 1 "\f[GIV]\s+1〝シャヴァス探偵事務所〞\s0\fP" aligned invis
} else {
.\" そばにお手本を置く
  if (show_guide) then {
    move right 0.01
    line down 1 "\f[GIV]\s+1\m[red]〝シャヴァス探偵事務所〞\m[]\s0\fP" aligned invis
    move to BOX.ne; move right 0.2 down 0.07
  }
.\" 「〝」の次の文字「シ」の位置を合わせる。
  move down 0.04
.\" 「”」を始まりのダブルミニュートとして使う。配置は \h と \v で調整する。
  line right 0.001 "\h'0.11i'\v'-0.5'\f[GR]\s+1\[u201D]\s0\fP"; move left 0.001
  line down 1 "\f[GIV]\s+1シャヴァス探偵事務所\s0\fP" aligned invis
.\" 「“」を終わりのダブルミニュートとして使う。
  line right 0.001 "\v'0.93'\f[GR]\s+1\[u201C]\s0\fP\h'0.03i'"; move left 0.001
}
.PE
.rt
.RS +16.5m
この字幕についてNHKの説明を添えておきます。
.ps
.ig
.PP
おたずねいただいた「昼下りの情事」開始5分ほどの、
\(lqシャヴァス探偵事務所\(rq という縦の字幕ですが、
台詞ではなく画面の文字の翻訳のため、
ダブルクォーテーションマークで、
文字も斜体にしています。
..
.PP
.rs
.sp .2
.vs -2p
.ft HR
この場面は、シャヴァスを演じるモーリス・シュヴァリエのナレーションがあり、
「生活はごくまともだ」「家族は娘と娘のチェロ」とナレーションの字幕もあります。
同じ画面に２つの字幕があるため、
台詞と区別するためダブルクォーテーションマークで斜体とし、
画面の邪魔にならないよう縦で表示いたしました。
.ft
.RE
.sp
.PP
字幕の書き方は、
.ft I
台詞 \(-> 正体、
ナレーションや補足説明等 \(-> 斜体、
補足説明は括弧や引用符類でくくる、
配置が難しい場合は書字方向を変える、
.ft
と要約できるかもしれません。
.
.PP
字幕の「\c
.UR https://www.compart.com/en/unicode/U+201D
\f[GR]\[u201D]\fP
.\".ps -1
.\"(Right Double Quotation Mark)
.\".ps
.UE 」
と「\c
.UR https://www.compart.com/en/unicode/U+201C
\f[GR]\[u201C]\fP
.\".ps -1
.\"(Left Double Quotation Mark)
.\".ps
.UE 」
は、
.ft HR
ダブルクォーテーションではなく、ダブルミニュートかと思われます。
字幕を制作したのが20年以上前で、
制作担当者に経緯や理由を確認できませんが、
(以下略)
.ft
ということでした。
.
.ig
.PD 0
.IP \u\s-2[3]\s0\d 3
.UR https://note.morisawa.co.jp/n/n2a43f2c09931#5ee13dc5-b559-44d5-af22-8b830c3eafb9
なんとなく使っていませんか？ 括弧の種類と使い分け
.UE
(モリサワ) の「横組・縦組で異なる字形」に使用例があります。
.IP \(bu 3
.UR https://helpx.adobe.com/jp/fonts/using/open-type-syntax.html#vert
opentype機能
.UE
.IP \(bu 3
HaranoAjiフォントで小書きのカタナカにはopentype機能のvknaを指定する。
.UR https://github.com/trueroad/HaranoAjiFonts
https://github.com/trueroad/HaranoAjiFonts
.UE
..
.
.\" ------------------------------------------------------------------
.SS 人名漢字
.\" ------------------------------------------------------------------
.
例として、「\[u9089]」と「\[u908A]」の異体字を示します。
.sp .3
.RS +2
.ps +14
.vs (u;\n[.s]p)u
\[u9089]\:\c
.\"\[u9089_E010F]\:\c
\[u9089_E0110]\:\c
\[u9089_E0111]\:\c
\[u9089_E0112]\:\c
\[u9089_E0113]\:\c
\[u9089_E0114]\:\c
\[u9089_E0115]\:\c
\[u9089_E0116]\:\c
\[u9089_E0117]\:\c
\[u9089_E0118]\:\c
\[u9089_E0119]\:\c
\[u9089_E011A]\:\c
\[u9089_E011B]\:\c
\[u9089_E011C]\:\c
\[u9089_E011D]\:\c
\[u9089_E011F]\:\c
.sp .2
\[u908A]\:\c
.\"\[u908A_E0108]\:\c
\[u908A_E0109]\:\c
\[u908A_E010A]\:\c
\[u908A_E010B]\:\c
\[u908A_E010C]\:\c
\[u908A_E010D]\:\c
\[u908A_E010E]\:\c
\[u908A_E010F]\:\c
\[u908A_E0110]\:\c
\[u908A_E0111]\:\c
\[u908A_E0112]\:\c
.ps
.vs
.RE
.
.IP \(bu 3
IPAmj明朝フォントは、\-e オプションを指定しなくても埋め込まれます。
