'\" tp
.\" -*- nroff -*-
.
.TH GROPDF-OTF 7
.
.am1 EX
.in +1m
.ps -0.5
.sp .3
.vs 13p
..
.am1 EE
.ps +0.5
.in -1m
.vs
..
.
.ds MF B\" man page topic font
.ds HF HB\" Default heading font
.
.
.\" ------------------------------------------------------------------
.SH NAME
.\" ------------------------------------------------------------------
.
gropdf-otf \- gropdfのOTFサポート (メモ)
.
.\" ------------------------------------------------------------------
.SH SYNOPSYS
.pdfhref M -N SYNOPSYS
.\" ------------------------------------------------------------------
.
日本語のOTFを使用して
groffで日本語のPDFを作成するubuntuのvagrant boxを作成します。
.EX
git clone https://github.com/obuk/gropdf-otf.git
cd gropdf-otf
vagrant up
vagrant ssh
cd /vagrant
.sp .5
# このメモやマンページをPDFで出力してみましょう。
make gropdf-otf.7.pdf
export GROFF_BIN_PATH=$HOME/bin
zcat $(man -Lja -w 7 groff) | groff -Tpdf -ktp -mja -mandoc - > a.pdf
env MANROFFOPT="-mja -dpaper=`paperconf`" man -Tpdf -Lja 7 groff >a.pdf
.ig
.\".sp .5
.\"# マンページのPDFを作成します。groffのオプションはMANROFFOPTに指定します。
.\"env MANROFFOPT="-dpaper=`paperconf` -P-yN" man -Tpdf -Lja 7 groff >a.pdf
..
.EE
.
.
.\" ------------------------------------------------------------------
.SH 日本語フォント
.\" ------------------------------------------------------------------
.
日本語のOTFを明朝M\fIx\fP、ゴチックG\fIx\fP、等幅GM\fIx\fP のgroffフォント
.\" .MR groff_font 5
としてインストールします。
M、G、GMはファミリの名前、\fIx\fP はスタイルの名前です。
太さ \(mu 形状 \(mu 書字方向の組み合せです。
.in +2
.nf
R	中字・正体・横書	V	中字・正体・縦書
.vs 15p
I	中字・斜体・横書	IV	中字・斜体・縦書
B	太字・正体・横書	BV	太字・正体・縦書
BI	太字・斜体・横書	BIV	太字・斜体・縦書
.vs
.fi
.in
.
.\".PP
.\"作成される日本語のgroffフォントは大きく、読み取りには時間がかかります。
.\"(設定だけでも読み取られます。)
.
.\" Notoフォントから作成したMRは177,761行、
.\" M\fIx\fP、G\fIx\fP、GM\fIx\fP を合計すると1,882,650行にもなります。
.\" このフォントを使用して groff(7) のPDFを作成するとおよそ20秒もかかります。
.
.
.ig
.IP \u\s-2[0]\s0\d 4
このリポジトリでは、日本語のOTFに
.UR https://github.com/trueroad/HaranoAjiFonts
原ノ味フォント
.UE \c
とNotoフォントを使用します。
..
.
.\" ------------------------------------------------------------------
.SS FOUNDRY の指定とフォントの埋め込み
.\" ------------------------------------------------------------------
.
.MR gropdf 1
はfoundryをサポートしています。これはgropdfのオプション \-y で
同じフォントの異なるバージョンを選択する仕組みだと説明されていますが、
別のフォントを選択するためにも使えそうです。
.PP
Notoフォントは、ubuntuでは標準の日本語フォントとしてインストールされ、
fonts-confも設定されます。従って、fonts-confを使用するPDFビューアは、
Notoフォントを選択すれば埋め込まなくても表示できる可能性があります。
(PDFのファイルサイズを小さくできる可能性があります。)
.PP
原ノ味フォントは、
源ノフォントをAdobe-Japan1フォントに合わせて組み替えたフォントですが、
縦書のグリフが調整されています。
たとえば、\&\f[CR]\s+2〝シャヴァス探偵事務所〞\s0\fP\&を
Notoフォントと原ノ味フォントの縦書で表示すると、
.
.sp .3
.RS +2
.vs (\n[.s]p * 150 / 100)u
.rs
.TS
tab(;);
l l.
T{
\f[X-GIV]〝シャヴァス探偵事務所〞\fP\u\s-2[1]\s0\d
T};T{
Notoフォント
T}
T{
\f[GIV]〝シャヴァス探偵事務所〞\fP
T};T{
原ノ味フォント
T}
.TE
.vs
.RE
.sp .3
ダブルミニュートの表示に違いがあることが分ります。
縦書のスタイルはfont-featureにvrt2を指定しました。
この結果を見ると、foundryでNotoフォントを選択した場合でも、
縦書の字体は原ノ味フォントの方が良さそうです。
.PD .2
.IP \u\s-2[1]\s0\d 3
この例はNotoフォントの縦書の斜体を X-GIV という名前でインストールしています。
.EX
make -f font-noto-cjk.mk FOUNDRY=X FAMILY=G STY=IV install
.EE
.ig
ダブルミニュートの説明は、
.UR https://note.morisawa.co.jp/n/n2a43f2c09931#5ee13dc5-b559-44d5-af22-8b830c3eafb9
括弧の種類と使い分け
.UE
(モリサワ) の「横組・縦組で異なる字形」の使用例が分りやすいと思います。
..
.PP
というわけで、次表のとおりインストールします。
.
.PP
.\" .ne 11
.RS +2
.\" .vs (\n[.s]p * 150 / 100)u
.rs
.\".sp .3
.vs 15p
.TS
tab(;);
lb lb lb lb lb
c c c l l.
Foundry;Embed;Family;Styles;FontName
_
;yes;M;R I B BI V IV BV BIV;HaranoAjiMincho-{Regular,Bold}
;yes;G;R I B BI V IV BV BIV;HaranoAjiGothic-{Regular,Bold}
;yes;GM;R I B BI;HaranoAjiGothic-{Regular,Bold}
_
N;no;M;R I B BI;NotoSerifCJKjp-{Regular,Bold}
N;no;G;R I B BI;NotoSansCJKjp-{Regular,Bold}
N;no;GM;R I B BI;NotoSansCJKjp-{Regular,Bold}
.TE
.\" .vs.bak
.vs
.RE
.
.PP
原ノ味フォントでもフォントを埋め込まないようにすることはできますが、
その場合、利用者が
.UR https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
fonts-conf
.UE
を設定する必要があります。
.\" 更に download ファイル中のパスの先頭に * を置きます。
.
.PP
また、gropdfでCFFのサブセットフォントの作成にpyftsubsetを呼び出すと、
man \-Tpdf では \f[CR]Fatal Python error: init_fs_encoding: ...\fP
というメッセージが出力されます。
とりあえず、
.UR https://github.com/obuk/font-ttf
Font::TTF
.UE
に同様の機能を追加して対処しました。XXXXX
.
.ig end-of-experiment
.\" ------------------------------------------------------------------
.SS フォントサイズを小さくするために分割する (実験)
.\" ------------------------------------------------------------------
.
日本語のフォントは多数のグリフで構成され、中にはほとんど使われないものもあります。
そこで、1つのフォントをよく使われるグリフの集まり (主フォント) と
それ以外 (副フォント) に分け、普段は前者のみを使用することで、
見かけのフォントサイズを小さくします。
.
「よく使われるグリフの集まり」には
.UR https://ja.wikipedia.org/wiki/JIS_X_0208
JIS X 0208
.UE
を選びました。
残念ながら頻用グリフ集合のようなものはないため、
文字集合の規格で小さなものを選択することになります。
.
.PP
また、OTFから作成したgroffフォントを調べると、
kernpairsセクションがかなりの量を占めることが分ります。
そこで、等幅フォント、副フォント、
およびfoundryで選択されるフォントではこのセクションを削除します。
.
.\" ------------------------------------------------------------------
.SS 分割フォントの使い方と作り方 (実験)
.\" ------------------------------------------------------------------
.
.PP
分割フォントの主フォントにない文字「令和 \f(CR\e[u32FF]\fP」のPDFを作成してみましょう。
.
.EX
.ne 3
# 主フォントのみを使用すると「令和」の未定義が警告されます。
echo "\ev[+20]\es[+200]\e[u32FF]\ef[MV]\e[u32FF]" |groff -Tpdf >a.pdf
troff:<standard input>:1: warning: special character 'u32FF' not defined
.sp .5
.ne 2
# 警告は、オプション \-rfn-s=1 \-rfn-v=1 で止めることができます。
echo "\ev[+20]\es[+200]\e[u32FF]\ef[MV]\e[u32FF]" |groff -Tpdf -rfn-s=1 -rfn-v=1 >a.pdf
.EE
.
.PP
オプションの \f(CR-rfn-s=1\fP は、ほとんど使わないグリフを、
\f(CR-rfn-v=1\fP は、縦書のグリフを使えるようにします。
フォントの分割に関する詳細は、font-common.mk を参照してください。
.
.PP
フォントの分割はスクリプトfilter-fontを使用します。
明朝体MRをMRとMR.sに分ける例を示します。
.EX
$ \f(CBfilter-font -012k MR >/tmp/MR\fP
$ \f(CBfilter-font -s -n MR.s >/tmp/MR.s\fP
.EE
.PP
filter-fontで利用可能なオプションは次のとおりです。
.RS +2
.PD 0
.IP \f(CR\-1\fP\~\f(CR\-2\fP 8
JIS第1水準、第2水準\u\s-2†\s0\dを出力する。
.IP \f(CR\-0\fP
基本的なグリフ (コード256未満) を出力する。
.IP \f(CR\-s\fP
それ以外 (\f(CR\-b12\fP 以外) を出力する。
.IP \f(CR\-k\fP 8
kernpairsセクションを出力する。
このセクションで補正されグリフをcharsetセクションに出力する。
.IP \f(CR\-n\fP
name行のフォント名を指定する。
.RE
.PD 0
.IP \u\s-2†\s0\d 3
.UR http://unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT
http://unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT
.UE
.end-of-experiment
.
.\" ------------------------------------------------------------------
.SS 実環境の利用
.\" ------------------------------------------------------------------
.
実環境にインストールします。仮想環境より少し速くなります。
寝ころんで紙を読む、綺麗な印刷物が好き、lprで印刷する、といった理由で実環境です。
必要でない限りやらない方が安全だと思います。
.PP
ここでは $HOME の下に groff, plenv, pyenv 等をインストールします。
まず、Mk/default.mk でバージョンとインストール先を自分用に設定し、
仮想環境で動作を確認します。
.EX
cd gropdf-otf
vi Mk/defaultl.mk
.\"PERL_VERSION?=	5.42.0
.\"PYTHON_VERSION?=	3.10.18
GROFF_VERSION?=	1.23.0
GROFF_PREFIX?=	${HOME}
MANDB_PREFIX?=	${HOME}
:q
vagrant destroy -f && vagrant up 
.EE
そして、できれば壊れても諦めがつく実環境にインストールします。
手順は以下のとおりです。
.EX
.ne 4
make -f groff.mk clean install
make -f site-tmac.mk clean install
make -f gropdf.mk clean install
.sp .5
.ne 6
# 必要なフォントをインストールします。
make -f font-haranoaji.mk clean install
make -f font-haranoaji-code.mk clean install
make -f font-noto-cjk.mk FOUNDRY=N clean install
make -f font-noto-code-cjk.mk FOUNDRY=N clean install
.\"make -f font-ipamj.mk clean install
.ig
.sp .5
.ne 7
# 十分に速いマシンではフォントを分割しないという選択肢もあるかもしれません。
export SPLIT=
make -f font-haranoaji.mk clean install
make -f font-haranoaji-code.mk clean install
make -f font-noto-cjk.mk FOUNDRY=N clean install
make -f font-noto-code-cjk.mk FOUNDRY=N clean install
unset SPLIT
..
.sp .5
.ne 3
# インストールしたgroffが使われるようにします。
vi ~/.profile
export GROFF_BIN_PATH=$HOME/bin
:wq
.EE
.
.
.\" ------------------------------------------------------------------
.SS スペシャルフォントの設定
.\" ------------------------------------------------------------------
.
日本語のフォントは、欧文フォントのスペシャルフォントとして設定します。
その際、グリフの大きさ (高さ) も設定します。
設定は $SITE_TMAC/ps.local にあります。
結果と合わせて示します。
.EX
\&.\e\[dq] T\fIx\fPのスペシャルフォントに\
M\fIx\fP(および M\fIx\fP.s)を設定します。
\&.my:fspecial TR  MR MI MB MBI
.EE
.sp -.5
.in +1m
.PS
d = 0.03
h = 0.308
w1 = 4.0
w2 = 1.5
w = 5.5
define top_and_bottom_lines {
move left w down d
line right w dotted
move left w down d
line right w dashed
move left w up h*$1
line right w dotted
move left w up d
line right w dashed
}
.ft CR
line right w1 "\ef[TR]\s[+20]\f[TR]ABC漢字かなカナ\fP\s[-20]\efP" invis
line right w2 "\ef[MR]\s[+20]\f[MR]XYZ\fP\s[-20]\efP" invis
.ft
top_and_bottom_lines(1)
.PE
.
.sp -.3
.PS
.ft CR
line right w1 "\ef[TB]\s[+20]\f[TB]ABC漢字かなカナ\fP\s[-20]\efP" invis
line right w2 "\ef[MB]\s[+20]\f[MB]XYZ\fP\s[-20]\efP" invis
.ft
top_and_bottom_lines(1)
.PE
.ig
.ft TR
上の例は、T\fIx\fP のスペシャルフォントに
M\fIx\fP (\fIx\fP = R, I, B, BI) を設定します。
その際、T\fIx\fP と M\fIx\fP の高さが揃うように
M\fIx\fP の倍率も設定します。
..
.
.PP
.rs
.EX
\&.\e\[dq]T\fIx\fPとH\fIx\fPの高さを揃えます。
\&.my:fzoom    TR  HR HI HB HBI
.sp .5
\&.\e\[dq]H\fIx\fPのスペシャルフォントを設定します。
\&.my:fspecial HR  GR GI GB GBI
.EE
.sp -.5
.in +1m
.PS
.ft CR
line right w1 "\ef[HR]\s[+20]\f[HR]ABC漢字かなカナ\fP\s[-20]\efP" invis
line right w2 "\ef[GR]\s[+20]\f[GR]XYZ\fP\s[-20]\efP" invis
.ft
top_and_bottom_lines(1)
.PE
.sp -.3
.PS
.ft CR
line right w1 "\ef[HB]\s[+20]\f[HB]ABC漢字かなカナ\fP\s[-20]\efP" invis
line right w2 "\ef[HB]\s[+20]\f[HB]XYZ\fP\s[-20]\efP" invis
.ft
top_and_bottom_lines(1)
.PE
.
.PP
.rs
.EX
.ne 3
\&.\e\[dq] C\fIx\fP の高さをT\fIx\fPの800/1000倍にします。\
(好みもありますが、コードの折り返しが減るように)
\&.nr CR.zoom 800
\&.my:fzoom    TR  CR CI CB CBI
.sp .5
.ne 2
\&.\e\[dq] \f(CREX/EE\fP ブロックの1行に納まる文字数を確かめてみましょう。
_________1_________2_________3_________4_________5_________6_________7______
1234567890123456789012345678901234567890123456789012345678901234567890123456
.sp .5
.ne 2
\&.\e\[dq] C\fIx\fPのスペシャルフォントを設定します。
\&.my:fspecial CR  GMR GMI GMB GMBI
.EE
.sp -.5
.in +1m
.PS
.ft CR
line right w1 "\ef[CR]\s[+20]\f[CR]ABC漢字かなカナ\fP\s[-20]\efP" invis
line right w2 "\ef[GMR]\s[+20]\f[GMR]XYZ\fP\s[-20]\efP" invis
.ft
top_and_bottom_lines(0.8)
.PE
.sp -.3
.PS
.ft CR
line right w1 "\ef[CB]\s[+20]\f[CB]ABC漢字かなカナ\fP\s[-20]\efP" invis
line right w2 "\ef[GMB]\s[+20]\f[GMB]XYZ\fP\s[-20]\efP" invis
.ft
top_and_bottom_lines(0.8)
.PE
.in
.sp .5
.PP
.EX
.ne 5
\&.\e\[dq] 縦書はコマンドラインで-rfn-v=1が指定された場合に設定します\
(フォントが読み取られます)。
\&.if \en[fn-v] \e{\e
\&.  my:fspecial2 TR  MV MIV MBV MBIV
\&.  my:fspecial2 HR  GV GIV GBV GBIV
\&.\e}
.EE
.sp -.5
.in +1m
.PS
.ft CR
.my:fspecial2 TR MV
line right w1 "\ef[MV]\s[+20]\f[MV]ABC漢字かなカナ\fP\s[-20]\efP" invis
line right w2 "\ef[MR]\s[+20]\f[MR]いろは\fP\s[-20]\efP" invis
.ft
top_and_bottom_lines(1)
.PE
.sp -.5
.PS
.ft CR
.my:fspecial2 HR GV
line right w1 "\ef[GV]\s[+20]\f[GV]ABC漢字かなカナ\fP\s[-20]\efP" invis
line right w2 "\ef[GR]\s[+20]\f[GR]いろは\fP\s[-20]\efP" invis
.ft
top_and_bottom_lines(1)
.PE
.
.ig
.\" ------------------------------------------------------------------
.SS 分割に JIS X 0208 を使用するのは妥当か
.\" ------------------------------------------------------------------
.
普段は、分割フォントの主フォントのみで十分であることを確かめたいと思いますが、
対象を定めるのは難しく、とりあえず日本語のマンページを使いました。
PDFの作成でグリフの未定義が警告されたページは次のとおり。
.
.sp 4p
.RS +2
.vs 13p
iconv.1
charsets.7
armscii-8.7
cp1251.7
.\" iso_8859-1.7 (latin1.7)
iso_8859-2.7\"(latin2.7)
iso_8859-3.7\"(latin3.7)
iso_8859-4.7\"(latin4.7)
iso_8859-5.7
iso_8859-6.7
iso_8859-7.7
iso_8859-8.7
.\" iso_8859-9.7 (latin5.7)
iso_8859-10.7\" (latin6.7)
iso_8859-11.7\" (tis-620.7)
iso_8859-13.7\" (latin7.7)
iso_8859-14.7\" (latin8.7)
.\" iso_8859-15.7 (latin9.7)
iso_8859-16.7\" (latin10.7)
koi8-r.7
koi8-u.7
.RE
.
.PP
警告は日本語のフォントにない文字のみでした。
..
.
.\" ------------------------------------------------------------------
.SH 日本語の表示例
.\" ------------------------------------------------------------------
.
.\" ------------------------------------------------------------------
.SS 縦書斜体
.\" ------------------------------------------------------------------
.
.
縦書斜体の使用例として、
NHK BS シネマ「昼下りの情事」から探偵事務所の看板とその字幕を示します
(開始から5分くらいのところにあります)。
珍しい字幕に驚き、つい質問したところ、以下のような回答が得られました。
.br
.ne 7
.mk
.in +1m
.PS
box_w = 1.8
box_h = 1.3
pin_r = 0.02
gap = 0.02
.vs 13p
BOX: box width box_w height box_h \
"" \
"\u\s+2CLAUDE CHAVASSE\s0\d" \
"\f(HR\s+2D\('EECTIVE PRIV\('E\s0\fP" \
"\f(HR\s-2DISCR\('ETION ASSUR\('EE\s0\fP" \
"\f(HR2\Z'\u\s-4\(`eme\s0\d'\h[0.4m]-\h[0.6m]E\s-2TAGE\s0\fP"
.vs
.\" pins at the corners
e2p = pin_r + gap
err = 0.07 + pin_r
move to BOX.nw down -err; move right e2p down  e2p; A: circle radius pin_r
move to BOX.sw down -err; move right e2p down -e2p; B: circle radius pin_r
move to BOX.se down -err; move left  e2p down -e2p; C: circle radius pin_r
move to BOX.ne down -err; move left  e2p down  e2p; D: circle radius pin_r
.\" lines between pins
hline_len = box_w - pin_r * 2 * 2 - gap * 2
vline_len = box_h - pin_r * 2 * 2 - gap * 2
move to A.b; move down  gap; AB: line down  vline_len - gap * 2
move to B.r; move right gap; BC: line right hline_len - gap * 2
move to C.t; move up    gap; CD: line up    vline_len - gap * 2
move to D.l; move left  gap; DA: line left  hline_len - gap * 2
.\" splines between lines
move to AB.b; spline right gap then right pin_r down  pin_r then down  gap
move to BC.r; spline up    gap then up    pin_r right pin_r then right gap
move to CD.t; spline left  gap then left  pin_r up    pin_r then up    gap
move to DA.l; spline down  gap then down  pin_r left  pin_r then left  gap
.\" subtitle
move to BOX.sw down 0.1
line right box_w "\f[HI]生活は ごくまともだ\fP" invis
.\" vertical subtitle
.\" cjk_puncts は原ノ味フォントのみ。Notoフォントは使えません。
cjk_puncts = 0
show_guide = 0
.\" コマンドラインで -rfn-s=1 や -rfn-v=1 が指定されない場合でも
.\" GIV と GIV.s が使えるようにします。
.if F GIV \{\
.  nr fn-s.bak \n[fn-s]
.  if F GIV.s .nr fn-s 1
.  my:fspecial2 HR GIV
.\}
move to BOX.ne; move right 0.2 down 0.07
.\" お手本を置く
if (show_guide) then {
  move right 0.15
  line down 1 "\f[GIV]\s+1\m[red]〝シャヴァス探偵事務所〞\m[]\s0\fP" aligned invis
  move to BOX.ne; move right 0.2 down 0.07
}
if (cjk_puncts) then {
  line down 1 "\f[GIV]\s+1〝シャヴァス探偵事務所〞\s0\fP" aligned invis
} else {
.\" 「〝」の次の文字「シ」の位置を合わせる。
  move down 0.07
.\" 「”」を始まりのダブルミニュートとして使う。配置は \h と \v で調整する。
  line right 0.001 "\h'0.11i'\v'-0.5'\f[GR]\s+1\[u201D]\s0\fP"; move left 0.001
  line down 1 "\f[GIV]\s+1シャヴァス探偵事務所\s0\fP" aligned invis
.\" 「“」を終わりのダブルミニュートとして使う。
  line right 0.001 "\v'0.93'\f[GR]\s+1\[u201C]\s0\fP\h'0.03i'"; move left 0.001
}
.PE
.in
.mk there
.rt
.RS +37n
.sp .5
.ps
.PP
.vs -2p
.ll -.5
.ft HR
この場面は、シャヴァスを演じるモーリス・シュヴァリエのナレーションがあり、
「生活はごくまともだ」「家族は娘と娘のチェロ」
とナレーションの字幕もあります。
同じ画面に２\&つの字幕があるため、
台詞と区別するためダブルクォーテーションマークで斜体とし、
画面の邪魔にならないよう縦で表示いたしました。
.ft
.ll
.vs
.RE
.mk here
.sp (u;\n[there] - \n[here])
.PP
当時のNHKの字幕制作システムの制約に関して質問してみたところ、
.PP
.ft HR
字幕の「\c
.UR https://www.compart.com/en/unicode/U+201D
\[u201D]
.\".ps -1
.\"(Right Double Quotation Mark)
.\".ps
.UE 」
と「\c
.UR https://www.compart.com/en/unicode/U+201C
\[u201C]
.\".ps -1
.\"(Left Double Quotation Mark)
.\".ps
.UE 」
は、
ダブルクォーテーションではなく、
ダブルミニュートかと思われます。\"\Z'。'\u\s-2[1]\s0\d
字幕を制作したのが20年以上前で、
制作担当者に経緯や理由を確認できませんが、
(以下略)
.ft
ということでした。
.
.ig
.IP \u\s-2[1]\s0\d 3
.UR https://note.morisawa.co.jp/n/n2a43f2c09931#5ee13dc5-b559-44d5-af22-8b830c3eafb9
括弧の種類と使い分け
.UE
(モリサワ) の「横組・縦組で異なる字形」に使用例があります。
..
.
.\" ------------------------------------------------------------------
.SS 人名漢字
.pdfhref M sample-ipamj
.\" ------------------------------------------------------------------
.
.ie F IPAmjMR \{\
.  ie \n[fnIPAmjMR] \{
例として、「\[u9089]」と「\[u908A]」の異体字を示します。
.sp .3
.RS +2
.ps +14
.vs \n[.s]p
\[u9089]\:\c
.\"\[u9089_E010F]\:\c
\[u9089_E0110]\:\c
\[u9089_E0111]\:\c
\[u9089_E0112]\:\c
\[u9089_E0113]\:\c
\[u9089_E0114]\:\c
\[u9089_E0115]\:\c
\[u9089_E0116]\:\c
\[u9089_E0117]\:\c
\[u9089_E0118]\:\c
\[u9089_E0119]\:\c
\[u9089_E011A]\:\c
\[u9089_E011B]\:\c
\[u9089_E011C]\:\c
\[u9089_E011D]\:\c
\[u9089_E011F]\:\c
.sp .2
\[u908A]\:\c
.\"\[u908A_E0108]\:\c
\[u908A_E0109]\:\c
\[u908A_E010A]\:\c
\[u908A_E010B]\:\c
\[u908A_E010C]\:\c
\[u908A_E010D]\:\c
\[u908A_E010E]\:\c
\[u908A_E010F]\:\c
\[u908A_E0110]\:\c
\[u908A_E0111]\:\c
\[u908A_E0112]\:\c
.ps
.vs
.RE
IPAmj明朝フォントは \-e オプションを指定しなくても埋め込まれます。
IPAmj明朝は原ノ味フォントより細いため、並べると違いが分ります。
.  \}
.  el \{
人名漢字のフォントIPAmj明朝はデフォルトで無効です。
.  \}
.\}
.el \{
人名漢字のフォントIPAmj明朝が見つかりません。
.\}
.
